from __future__ import annotations

from typing import Dict

from .models import RuntimeSpec

RUNTIMES: Dict[str, RuntimeSpec] = {
    "python": RuntimeSpec(
        key="python",
        label="Python Capsule",
        kind="python",
        default_file="main.py",
        run_command=["python", "main.py"],
        preview="terminal",
        targets=["wasi", "native", "github", "artifact"],
        deploy_modes=["agent", "service", "capsule"],
        server_enabled=True,
        wasm_candidate=True,
        toolchain_hint="CPython locally; WASI/Pyodide when the host toolchain is installed.",
    ),
    "html": RuntimeSpec(
        key="html",
        label="HTML Website Capsule",
        kind="html",
        default_file="index.html",
        run_command=["serve-static"],
        preview="web",
        targets=["browser", "web-worker", "github"],
        deploy_modes=["app", "web-worker", "capsule"],
        server_enabled=True,
        wasm_candidate=False,
        toolchain_hint="Served directly through the preview server.",
    ),
    "node": RuntimeSpec(
        key="node",
        label="Node Service Capsule",
        kind="javascript",
        default_file="main.js",
        run_command=["node", "main.js"],
        preview="api",
        targets=["node", "web-worker", "github"],
        deploy_modes=["service", "agent", "capsule"],
        server_enabled=True,
        wasm_candidate=False,
        toolchain_hint="Node runtime required for local execution.",
    ),
    "react": RuntimeSpec(
        key="react",
        label="React App Capsule",
        kind="react",
        default_file="src/App.tsx",
        run_command=["npm", "run", "dev"],
        preview="web",
        targets=["browser", "web-worker", "github"],
        deploy_modes=["app", "web-worker", "capsule"],
        server_enabled=True,
        wasm_candidate=False,
        toolchain_hint="Vite and npm dependencies required for full React execution.",
    ),
    "cpp": RuntimeSpec(
        key="cpp",
        label="C++ WASM Core Capsule",
        kind="cpp",
        default_file="main.cpp",
        run_command=["c++", "-std=c++17", "main.cpp", "-o", "main"],
        preview="terminal",
        targets=["wasm", "native", "web-worker", "github"],
        deploy_modes=["web-worker", "agent", "capsule"],
        server_enabled=False,
        wasm_candidate=True,
        toolchain_hint="Native C++ compiler for local builds; Emscripten or WASI SDK for WASM.",
    ),
    "c": RuntimeSpec(
        key="c",
        label="C WASM Core Capsule",
        kind="c",
        default_file="main.c",
        run_command=["cc", "main.c", "-o", "main"],
        preview="terminal",
        targets=["wasm", "native", "web-worker", "github"],
        deploy_modes=["web-worker", "agent", "capsule"],
        server_enabled=False,
        wasm_candidate=True,
        toolchain_hint="C compiler locally; Emscripten or WASI SDK for WASM.",
    ),
    "java": RuntimeSpec(
        key="java",
        label="Java Agent Capsule",
        kind="java",
        default_file="Main.java",
        run_command=["javac", "Main.java"],
        preview="terminal",
        targets=["native", "wasm", "github"],
        deploy_modes=["agent", "service", "capsule"],
        server_enabled=True,
        wasm_candidate=True,
        toolchain_hint="JDK for local execution; TeaVM/CheerpJ style bridge for web targets.",
    ),
    "julia": RuntimeSpec(
        key="julia",
        label="Julia Scientific Capsule",
        kind="julia",
        default_file="main.jl",
        run_command=["julia", "main.jl"],
        preview="notebook",
        targets=["native", "github", "artifact"],
        deploy_modes=["service", "report-suite", "capsule"],
        server_enabled=True,
        wasm_candidate=False,
        toolchain_hint="Julia runtime required; outputs are packaged as scientific artifacts.",
    ),
    "matlab": RuntimeSpec(
        key="matlab",
        label="MATLAB/Octave Scientific Capsule",
        kind="matlab",
        default_file="main.m",
        run_command=["octave", "main.m"],
        preview="artifact",
        targets=["native", "github", "artifact"],
        deploy_modes=["report-suite", "service", "capsule"],
        server_enabled=True,
        wasm_candidate=False,
        toolchain_hint="Octave-compatible local runner; MATLAB engine can be attached by host.",
    ),
}


def get_runtime(key: str) -> RuntimeSpec:
    if key not in RUNTIMES:
        choices = ", ".join(sorted(RUNTIMES))
        raise KeyError(f"unknown runtime '{key}'. Available: {choices}")
    return RUNTIMES[key]
